service: example2

provider:
    name: aws
    region: us-east-2
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref

functions:
    hello:
        handler: index.php
        description: ''
        layers:
            - ${bref:layer.php-74}
            - ${bref:layer.console}

# Exclude files from deployment
package:
    exclude:
        - 'tests/**'
